name: Publish Worker

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    publish_worker:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: latest
                  run_install: true

            - name: Build Worker
              run: pnpm build

            - name: Publish to Cloudflare
              run: pnpm wrangler publish
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }} # This is not necessary if "account_id" is set in the wrangler.toml.
